export type Kind='online_quiz'|'offline_quiz'|'activity'|'exam'|'manual';
export const KIND_LABEL:Record<Kind,string>={online_quiz:'Online quiz',offline_quiz:'Paper quiz',activity:'Activity',exam:'Examination',manual:'Teacher-evaluated'};
export type QType='multiple_choice'|'true_false'|'short_answer';
export interface Choice{id:string;text:string}
export interface Question{key:string;type:QType;prompt:string;choices:Choice[];correct:string|boolean|string[]|null;explanation:string;points:number|string;source?:{item_id:string;revision_id?:string;title:string}|null}
export interface AssessmentRev{version:number;state:string;counter:number;title:string;instructions:string;category_key:string|null;period:'midterm'|'finals'|null;max_points:number;available_from:string|null;deadline:string|null;allow_late:boolean;max_attempts:number;score_rule:'highest'|'latest';include_in_grade:boolean;anchor_node_id:string|null;updated_at:string;published_at:string|null;ai_generated?:boolean;ai_language?:string|null;reviewed?:boolean;questions:Question[]}
export interface Assessment{id:string;kind:Kind;archived:boolean;section_ids:string[];has_attempts:boolean;published:AssessmentRev|null;draft:AssessmentRev|null}
export interface DraftContent{title:string;instructions:string;category_key:string;period:string;max_points:string;available_from:string;deadline:string;allow_late:boolean;max_attempts:number;score_rule:'highest'|'latest';include_in_grade:boolean;anchor_node_id:string|null;questions:Question[]}
export interface ScoreRow{student_id:string;student:string;student_number:string;versions:number;latest:{version:number;submitted_at:string;is_late:boolean;note:string;file:{id:string;name:string;size:number}}|null;score:number|null;feedback:string;score_revision:number;graded_current_version:boolean;new_version_since_grading:boolean;permission_open:boolean}
export interface AttemptRow{id:string;student_id:string;student:string;student_number:string;attempt_number:number;state:'in_progress'|'submitted';score:number|null;max_score:number|null;submitted_at:string|null}
export interface AttemptDetail{id:string;student_id:string;state:string;attempt_number:number;score:number|null;max_score:number|null;questions:{key:string;type:QType;prompt:string;choices:Choice[];correct:unknown;points:number;response:unknown;auto_awarded:number|null;awarded:number|null;correction_reason:string|null}[]}
export interface Cell{score:number|null;feedback:string;revision:number;released_score:number|null;release_number:number;unreleased_change:boolean;attempt_state?:'not_attempted'|'in_progress'|'submitted'}
export interface CategoryInfo{key:string;label:string;weight:number;status:'ok'|'pending'|'no_data';earned:number|null;possible:number|null;raw_percent:number|null;percent:number|null;missing:string[]}
export interface PeriodGrade{grade:number|null;pending:string[];categories:CategoryInfo[]}
export interface PublishedGrade{grade:number;release_number:number;needs_review:boolean;review_reason:string|null}
export interface GradeRow{student_id:string;display_name:string;student_number:string;section:string|null;cells:Record<string,Cell>;grades:Record<string,PeriodGrade>;published:Record<string,PublishedGrade>}
export interface Gradebook{policy:{categories:{key:string;label:string;weight:number}[];periods:{key:string;label:string;share:number}[];transmutation:string;passing:number};policy_version:number;columns:{id:string;kind:Kind;title:string;category_key:string|null;period:string|null;max_points:number;include_in_grade:boolean}[];rows:GradeRow[]}
export interface AttendanceSessionRow{id:string;section_id:string;date:string;period:'midterm'|'finals';marks:Record<string,string>}
export interface LearnItem{id:string;kind:'online_quiz'|'activity';title:string;instructions:string;available_from:string|null;deadline:string|null;allow_late:boolean;max_points:number;result:{score:number;max_points:number;feedback:string;released_at:string}|null;state:string;max_attempts?:number;attempts_used?:number;in_progress_attempt_id?:string|null;submissions?:{version:number;submitted_at:string;is_late:boolean;note:string;file:{id:string;name:string;size:number}}[];can_submit?:boolean;would_be_late?:boolean;bucket:'todo'|'again'|'upcoming'|'awaiting'|'done'|'closed';late_allowed:boolean}
export interface AttemptView{id:string;state:'in_progress'|'submitted';attempt_number:number;questions:{key:string;type:QType;prompt:string;choices:Choice[];points:number}[];answers:Record<string,unknown>;score?:number;max_score?:number;answers_ignored?:boolean}
export interface Results{results:{assessment_id:string;kind:Kind;title:string;score:number;max_points:number;feedback:string;released_at:string;release_number:number}[];grades:{period:string;grade:number;remark:string;release_number:number;published_at:string}[]}
export const fmt=(n:number|null|undefined)=>n===null||n===undefined?'—':Number(n).toFixed(2);
export const toIso=(local:string)=>local?new Date(local).toISOString():null;
export const toLocal=(iso:string|null)=>{if(!iso)return '';const d=new Date(iso);const p=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
export const when=(iso:string|null)=>iso?new Date(iso).toLocaleString():'';
export const PERIOD_LABEL:Record<string,string>={midterm:'Midterm',finals:'Finals',course:'Course'};
