"""The data of a grade export, independent of the file format.

Two bases, never mixed in one file:
  published - the latest RELEASE per student (what students can see). Students with no release
              are listed as "Not published".
  working   - today's calculated values. Always marked as a preview, because students cannot
              see them and faculty may still change the inputs."""
from decimal import Decimal
from zoneinfo import ZoneInfo

from sqlalchemy import select

from app.config import settings
from app.errors import fail
from app.features.academics.models import AcademicTerm, OfferingSection, Section, Subject
from app.features.accounts.models import now
from app.features.assessments import grading

PERIOD_LABELS = {"midterm": "Midterm", "finals": "Finals", "course": "Course (overall)"}
NOT_OFFICIAL = "Generated by LearnSync. This is not an official institutional form."
PREVIEW = "PREVIEW - NOT PUBLISHED. Students cannot see these values and they may still change."


def number(value):
    return None if value is None else float(Decimal(str(value)))


def local_stamp(at):
    return at.astimezone(ZoneInfo(settings().app_timezone)).strftime("%Y-%m-%d %H:%M")


def describe(version, policy):
    scores = "transmuted" if policy.get("transmutation") == "transmuted" else "raw"
    return f"version {version}; passing grade {policy.get('passing', 75)}; {scores} scores"


def policy_line(policies, ctx):
    return " | ".join(describe(v, p) for v, p in sorted(policies.items())) + " (as released)"


def grade_table(db, actor, offering, period, basis, section_id, rank=False):
    ctx = grading.Context(db, offering)
    keys = [p["key"] for p in ctx.policy["periods"]]
    if period != "course" and period not in keys:
        fail(422, "period_invalid", "That grading period is not in the grading policy.")
    if basis not in ("published", "working"):
        fail(422, "basis_invalid", "Choose published grades or a working preview.")
    sections = {s.id: s.name for s in db.scalars(
        select(Section).join(OfferingSection, OfferingSection.section_id == Section.id)
        .where(OfferingSection.offering_id == offering.id).order_by(Section.name))}
    if section_id is not None and section_id not in sections:
        fail(422, "section_invalid", "Choose a section of this subject.")
    subject = db.get(Subject, offering.subject_id)
    term = db.get(AcademicTerm, offering.term_id)
    published = grading.latest_grade_rows(db, offering.id)
    flags = grading.review_flags(db, offering.id)
    chosen = {sid: g for (sid, p), g in published.items() if p == period} if basis == "published" else {}
    policies = {}                       # policy version -> the policy as it was when RELEASED
    for g in chosen.values():
        policies.setdefault(g.policy_version, (g.snapshot or {}).get("policy") or ctx.policy)
    if period == "course":
        suffix = " (used for this Course release)" if basis == "published" else ""
        value_columns = [(f"{PERIOD_LABELS[k]} grade{suffix}", k) for k in keys]
    else:
        seen = {}
        for source in ([ctx.policy] if basis == "working" or not policies else list(policies.values())):
            for c in source["categories"]:
                seen.setdefault(c["key"], c["label"])
        value_columns = [(f"{label} (%)", key) for key, label in seen.items()]
    mixed = len(policies) > 1
    columns = ["Student no.", "Name", "Section", *[label for label, _ in value_columns],
              *(["Policy version"] if mixed else []), "Grade", "Remark", "Status"]
    rows, ids, counts = [], [], {"published": 0, "not_published": 0, "preview": 0, "pending": 0}
    for enrollment, account in ctx.enrollments:
        if section_id is not None and enrollment.section_id != section_id:
            continue
        ids.append(account.id)                  # one row is appended below for every student kept here
        head = [account.student_number or "", account.display_name, sections.get(enrollment.section_id, "")]
        if basis == "published":
            release = published.get((account.id, period))
            if release is None:
                rows.append([*head, *[None] * len(value_columns), *([None] if mixed else []),
                             None, "", "Not published"])
                counts["not_published"] += 1
                continue
            periods = (release.snapshot or {}).get("periods", {})
            values = []
            for _, key in value_columns:
                if period == "course":
                    values.append(number(periods.get(key, {}).get("grade")))
                else:
                    cats = {c["key"]: c for c in periods.get(period, {}).get("categories", [])}
                    values.append(number(cats.get(key, {}).get("percent")))
            status = f"Published release {release.release_number} ({local_stamp(release.published_at)})"
            if (account.id, period) in flags:
                status += "; working data changed since, review pending"
            rows.append([*head, *values, *([release.policy_version] if mixed else []),
                         number(release.grade), release.remark, status])
            counts["published"] += 1
        else:
            result = grading.student_grades(ctx, enrollment)[period]
            if period == "course":
                others = grading.student_grades(ctx, enrollment)
                values = [number(others[k]["grade"]) for _, k in value_columns]
            else:
                cats = {c["key"]: c for c in result["categories"]}
                values = [number(cats[k]["percent"]) for _, k in value_columns]
            if result["grade"] is None:
                rows.append([*head, *values, None, "", "Pending: " + "; ".join(result["pending"])])
                counts["pending"] += 1
            else:
                rows.append([*head, *values, number(result["grade"]),
                             grading.remark(ctx, result["grade"]), "Working value (preview)"])
                counts["preview"] += 1
    meta = [
        ("Subject", f"{subject.code} - {subject.title}"),
        ("Term", term.name),
        ("Sections", sections.get(section_id) if section_id else ", ".join(sections.values()) or "None"),
        ("Period", PERIOD_LABELS[period]),
        ("Basis", "Published grades (latest release per student)" if basis == "published"
         else "Working values (preview)"),
        ("Grading policy", policy_line(policies, ctx) if basis == "published" and policies
         else describe(ctx.version, ctx.policy) + " (current)"),
        ("Generated", f"{local_stamp(now())} ({settings().app_timezone}) by {actor.display_name}"),
        ("Students", str(len(rows))),
    ]
    notes = [NOT_OFFICIAL]
    if mixed:
        notes.append("Releases in this file were made under different grading policy versions; each "
                     "row shows the version it was released under.")
    if basis == "working":
        notes.append("Pending students are missing required scores or attendance; nothing is guessed.")
    table = {"title": f"{subject.code} grades - {PERIOD_LABELS[period]}",
             "banner": PREVIEW if basis == "working" else None, "meta": meta, "notes": notes,
             "columns": columns, "rows": rows, "student_ids": ids, "counts": counts,
             "filename": f"grades-{subject.code}-{period}-{basis}"}
    if rank:
        scope = sections.get(section_id) if section_id else "all sections of this offering"
        add_rank(table, scope, period, basis)
    return table


def competition_ranks(grades):
    """Standard competition ranking on the two-decimal grade: 1, 2, 2, 4. Missing grades are not ranked."""
    ordered = sorted((round(g, 2) for g in grades if g is not None), reverse=True)
    first = {}
    for position, value in enumerate(ordered, start=1):
        first.setdefault(value, position)
    return [None if g is None else first[round(g, 2)] for g in grades]


def add_rank(table, scope, period, basis):
    """A Rank column in front of the table, rows ordered by rank (unranked students last, by name). The same
    function feeds the Class standing page and its exports, so they cannot disagree. Descriptive only: no curve,
    no honours, never shown to students."""
    grades = [r[-3] for r in table["rows"]]                  # the Grade column: published release or working value
    ranks = competition_ranks(grades)
    order = sorted(range(len(grades)), key=lambda i: (ranks[i] is None, ranks[i] or 0, table["rows"][i][1].lower()))
    table["rows"] = [[ranks[i], *table["rows"][i]] for i in order]
    table["student_ids"] = [table["student_ids"][i] for i in order]
    table["columns"] = ["Rank", *table["columns"]]
    ranked = [g for g in grades if g is not None]
    passed = sum(1 for r in table["rows"] if r[0] is not None and r[-2] == "passed")
    table["ranking"] = {
        "scope": scope, "ranked": len(ranked), "unranked": len(grades) - len(ranked), "passed": passed,
        "average": round(sum(ranked) / len(ranked), 2) if ranked else None,
        "highest": max(ranked) if ranked else None, "lowest": min(ranked) if ranked else None}
    basis_label = "published grades" if basis == "published" else "working preview"
    summary = (f"Rank within {scope}, based on {PERIOD_LABELS[period]} {basis_label}. "
               f"{len(ranked)} students ranked; {len(grades) - len(ranked)} unranked. "
               "Ties use competition ranking (1, 2, 2, 4).")
    table["meta"].append(("Ranking", summary))
    table["notes"].append("Ranking is descriptive: it orders the grades shown, applies no curve, and is not "
                          "shown to students. Search or filters on screen never limit this file.")

