"""study message analogy"""
from alembic import op
import sqlalchemy as sa

revision = '0ddf61490d8e'
down_revision = 'dd341f0c7da5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_message', sa.Column('analogy', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_message', 'analogy')
    # ### end Alembic commands ###
