"""Academic administration"""
from alembic import op
import sqlalchemy as sa

revision = '23bd97b89037'
down_revision = '928ad3c21a6f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_year',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('subject',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('units', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('year_level', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.CheckConstraint("status IN ('active','archived')", name='subject_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('academic_term',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('reopened_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('open','closed')", name='term_status'),
    sa.CheckConstraint('end_date >= start_date', name='term_dates'),
    sa.ForeignKeyConstraint(['closed_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_year.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_year_id', 'sequence', name='term_sequence_unique')
    )
    op.create_index(op.f('ix_academic_term_school_year_id'), 'academic_term', ['school_year_id'], unique=False)
    op.create_table('offering',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('faculty_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active','archived')", name='offering_status'),
    sa.ForeignKeyConstraint(['faculty_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'term_id', 'faculty_id', name='offering_unique')
    )
    op.create_index(op.f('ix_offering_faculty_id'), 'offering', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_offering_subject_id'), 'offering', ['subject_id'], unique=False)
    op.create_index(op.f('ix_offering_term_id'), 'offering', ['term_id'], unique=False)
    op.create_table('section',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('year_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'name', name='section_name_unique')
    )
    op.create_index(op.f('ix_section_term_id'), 'section', ['term_id'], unique=False)
    op.create_table('enrollment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('regular','exception')", name='enrollment_source'),
    sa.CheckConstraint("status IN ('enrolled','withdrawn')", name='enrollment_status'),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id', 'student_id', name='enrollment_unique')
    )
    op.create_index(op.f('ix_enrollment_offering_id'), 'enrollment', ['offering_id'], unique=False)
    op.create_index(op.f('ix_enrollment_student_id'), 'enrollment', ['student_id'], unique=False)
    op.create_table('enrollment_exception',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action <> 'include' OR section_id IS NOT NULL", name='include_needs_section'),
    sa.CheckConstraint("action IN ('include','exclude')", name='enrollment_exception_action'),
    sa.ForeignKeyConstraint(['actor_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id', 'student_id', name='enrollment_exception_unique')
    )
    op.create_index(op.f('ix_enrollment_exception_offering_id'), 'enrollment_exception', ['offering_id'], unique=False)
    op.create_table('offering_section',
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('offering_id', 'section_id')
    )
    op.create_table('section_member',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active','withdrawn')", name='section_member_status'),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_term.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'student_id', name='section_member_unique')
    )
    op.create_index(op.f('ix_section_member_section_id'), 'section_member', ['section_id'], unique=False)
    op.create_index(op.f('ix_section_member_student_id'), 'section_member', ['student_id'], unique=False)
    op.create_index('one_active_section_per_term', 'section_member', ['term_id', 'student_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('one_active_section_per_term', table_name='section_member', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_section_member_student_id'), table_name='section_member')
    op.drop_index(op.f('ix_section_member_section_id'), table_name='section_member')
    op.drop_table('section_member')
    op.drop_table('offering_section')
    op.drop_index(op.f('ix_enrollment_exception_offering_id'), table_name='enrollment_exception')
    op.drop_table('enrollment_exception')
    op.drop_index(op.f('ix_enrollment_student_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_offering_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_section_term_id'), table_name='section')
    op.drop_table('section')
    op.drop_index(op.f('ix_offering_term_id'), table_name='offering')
    op.drop_index(op.f('ix_offering_subject_id'), table_name='offering')
    op.drop_index(op.f('ix_offering_faculty_id'), table_name='offering')
    op.drop_table('offering')
    op.drop_index(op.f('ix_academic_term_school_year_id'), table_name='academic_term')
    op.drop_table('academic_term')
    op.drop_table('subject')
    op.drop_table('school_year')
    # ### end Alembic commands ###
