"""Assessments attempts submissions scores attendance and grade publications"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '559daccd3b81'
down_revision = 'f8b2e20a48f0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=14), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('online_quiz','offline_quiz','activity','exam','manual')", name='assessment_kind'),
    sa.ForeignKeyConstraint(['created_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_offering_id'), 'assessment', ['offering_id'], unique=False)
    op.create_table('attendance_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("period IN ('midterm','finals')", name='attendance_period'),
    sa.ForeignKeyConstraint(['created_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id', 'section_id', 'session_date', name='attendance_day')
    )
    op.create_index(op.f('ix_attendance_session_offering_id'), 'attendance_session', ['offering_id'], unique=False)
    op.create_table('grade_publication',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('release_number', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('remark', sa.String(length=10), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("period IN ('midterm','finals','course')", name='grade_period'),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id', 'student_id', 'period', 'release_number', name='grade_release_unique')
    )
    op.create_index(op.f('ix_grade_publication_offering_id'), 'grade_publication', ['offering_id'], unique=False)
    op.create_index(op.f('ix_grade_publication_student_id'), 'grade_publication', ['student_id'], unique=False)
    op.create_table('grade_review_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id', 'student_id', 'period', name='review_context_unique')
    )
    op.create_index(op.f('ix_grade_review_state_offering_id'), 'grade_review_state', ['offering_id'], unique=False)
    op.create_table('assessment_revision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('draft_counter', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('category_key', sa.String(length=40), nullable=True),
    sa.Column('period', sa.String(length=10), nullable=True),
    sa.Column('max_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allow_late', sa.Boolean(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('score_rule', sa.String(length=8), nullable=False),
    sa.Column('include_in_grade', sa.Boolean(), nullable=False),
    sa.Column('anchor_node_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("period IS NULL OR period IN ('midterm','finals')", name='assessment_period'),
    sa.CheckConstraint("score_rule IN ('highest','latest')", name='assessment_score_rule'),
    sa.CheckConstraint("state IN ('draft','published','superseded')", name='assessment_state'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'version', name='assessment_version_unique')
    )
    op.create_index(op.f('ix_assessment_revision_assessment_id'), 'assessment_revision', ['assessment_id'], unique=False)
    op.create_index('one_assessment_draft', 'assessment_revision', ['assessment_id'], unique=True, postgresql_where=sa.text("state = 'draft'"))
    op.create_index('one_assessment_published', 'assessment_revision', ['assessment_id'], unique=True, postgresql_where=sa.text("state = 'published'"))
    op.create_table('assessment_section',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('assessment_id', 'section_id')
    )
    op.create_table('attendance_mark',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.CheckConstraint("status IN ('present','absent','late','excused')", name='attendance_status'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_session.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='attendance_mark_unique')
    )
    op.create_index(op.f('ix_attendance_mark_session_id'), 'attendance_mark', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_mark_student_id'), 'attendance_mark', ['student_id'], unique=False)
    op.create_table('result_publication',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('release_number', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'student_id', 'release_number', name='result_release_unique')
    )
    op.create_index(op.f('ix_result_publication_assessment_id'), 'result_publication', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_result_publication_student_id'), 'result_publication', ['student_id'], unique=False)
    op.create_table('submission_permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_permission_assessment_id'), 'submission_permission', ['assessment_id'], unique=False)
    op.create_table('activity_submission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['stored_file.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['assessment_revision.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'student_id', 'version', name='submission_version_unique')
    )
    op.create_index(op.f('ix_activity_submission_assessment_id'), 'activity_submission', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_activity_submission_student_id'), 'activity_submission', ['student_id'], unique=False)
    op.create_table('quiz_attempt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.CheckConstraint("state IN ('in_progress','submitted')", name='attempt_state'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['assessment_revision.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'student_id', 'attempt_number', name='attempt_number_unique')
    )
    op.create_index(op.f('ix_quiz_attempt_assessment_id'), 'quiz_attempt', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempt_student_id'), 'quiz_attempt', ['student_id'], unique=False)
    op.create_index('one_attempt_in_progress', 'quiz_attempt', ['assessment_id', 'student_id'], unique=True, postgresql_where=sa.text("state = 'in_progress'"))
    op.create_table('quiz_question',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('choices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.CheckConstraint("type IN ('multiple_choice','true_false','short_answer')", name='question_type'),
    sa.ForeignKeyConstraint(['revision_id'], ['assessment_revision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'key', name='question_key_unique')
    )
    op.create_index(op.f('ix_quiz_question_revision_id'), 'quiz_question', ['revision_id'], unique=False)
    op.create_table('assessment_score',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('selected_attempt_id', sa.UUID(), nullable=True),
    sa.Column('selected_submission_id', sa.UUID(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('graded_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score IS NULL OR score >= 0', name='score_non_negative'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['graded_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['selected_attempt_id'], ['quiz_attempt.id'], ),
    sa.ForeignKeyConstraint(['selected_submission_id'], ['activity_submission.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'student_id', name='score_unique')
    )
    op.create_index(op.f('ix_assessment_score_assessment_id'), 'assessment_score', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_score_student_id'), 'assessment_score', ['student_id'], unique=False)
    op.create_table('quiz_answer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_key', sa.String(length=36), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_awarded', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('awarded', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('corrected_by', sa.UUID(), nullable=True),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempt.id'], ),
    sa.ForeignKeyConstraint(['corrected_by'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_key', name='answer_unique')
    )
    op.create_index(op.f('ix_quiz_answer_attempt_id'), 'quiz_answer', ['attempt_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_answer_attempt_id'), table_name='quiz_answer')
    op.drop_table('quiz_answer')
    op.drop_index(op.f('ix_assessment_score_student_id'), table_name='assessment_score')
    op.drop_index(op.f('ix_assessment_score_assessment_id'), table_name='assessment_score')
    op.drop_table('assessment_score')
    op.drop_index(op.f('ix_quiz_question_revision_id'), table_name='quiz_question')
    op.drop_table('quiz_question')
    op.drop_index('one_attempt_in_progress', table_name='quiz_attempt', postgresql_where=sa.text("state = 'in_progress'"))
    op.drop_index(op.f('ix_quiz_attempt_student_id'), table_name='quiz_attempt')
    op.drop_index(op.f('ix_quiz_attempt_assessment_id'), table_name='quiz_attempt')
    op.drop_table('quiz_attempt')
    op.drop_index(op.f('ix_activity_submission_student_id'), table_name='activity_submission')
    op.drop_index(op.f('ix_activity_submission_assessment_id'), table_name='activity_submission')
    op.drop_table('activity_submission')
    op.drop_index(op.f('ix_submission_permission_assessment_id'), table_name='submission_permission')
    op.drop_table('submission_permission')
    op.drop_index(op.f('ix_result_publication_student_id'), table_name='result_publication')
    op.drop_index(op.f('ix_result_publication_assessment_id'), table_name='result_publication')
    op.drop_table('result_publication')
    op.drop_index(op.f('ix_attendance_mark_student_id'), table_name='attendance_mark')
    op.drop_index(op.f('ix_attendance_mark_session_id'), table_name='attendance_mark')
    op.drop_table('attendance_mark')
    op.drop_table('assessment_section')
    op.drop_index('one_assessment_published', table_name='assessment_revision', postgresql_where=sa.text("state = 'published'"))
    op.drop_index('one_assessment_draft', table_name='assessment_revision', postgresql_where=sa.text("state = 'draft'"))
    op.drop_index(op.f('ix_assessment_revision_assessment_id'), table_name='assessment_revision')
    op.drop_table('assessment_revision')
    op.drop_index(op.f('ix_grade_review_state_offering_id'), table_name='grade_review_state')
    op.drop_table('grade_review_state')
    op.drop_index(op.f('ix_grade_publication_student_id'), table_name='grade_publication')
    op.drop_index(op.f('ix_grade_publication_offering_id'), table_name='grade_publication')
    op.drop_table('grade_publication')
    op.drop_index(op.f('ix_attendance_session_offering_id'), table_name='attendance_session')
    op.drop_table('attendance_session')
    op.drop_index(op.f('ix_assessment_offering_id'), table_name='assessment')
    op.drop_table('assessment')
    # ### end Alembic commands ###
