"""issue reports"""
from alembic import op
import sqlalchemy as sa

revision = 'c1cc39ea1b74'
down_revision = 'd577a614444a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('page', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open','in_progress','resolved')", name='issue_status'),
    sa.CheckConstraint("type IN ('bug','account','content','other')", name='issue_type'),
    sa.ForeignKeyConstraint(['reporter_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_report_created_at'), 'issue_report', ['created_at'], unique=False)
    op.create_index(op.f('ix_issue_report_reporter_id'), 'issue_report', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_issue_report_status'), 'issue_report', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_report_status'), table_name='issue_report')
    op.drop_index(op.f('ix_issue_report_reporter_id'), table_name='issue_report')
    op.drop_index(op.f('ix_issue_report_created_at'), table_name='issue_report')
    op.drop_table('issue_report')
    # ### end Alembic commands ###
