"""index state on item revisions"""
from alembic import op
import sqlalchemy as sa

revision = 'd577a614444a'
down_revision = 'e9266f8088cb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_item_revision', sa.Column('index_state', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_item_revision', 'index_state')
    # ### end Alembic commands ###
