"""quiz language on ai drafts"""
from alembic import op
import sqlalchemy as sa

revision = 'e67a8c8e4e4a'
down_revision = 'c1cc39ea1b74'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_revision', sa.Column('ai_language', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_revision', 'ai_language')
    # ### end Alembic commands ###
