"""Study chunks conversations ai generation progress events"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = 'e9266f8088cb'
down_revision = '559daccd3b81'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("event_type IN ('lesson_completed','quiz_submitted','activity_submitted')", name='event_type'),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'event_type', 'ref_id', name='event_unique')
    )
    op.create_index(op.f('ix_learning_event_occurred_at'), 'learning_event', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_learning_event_offering_id'), 'learning_event', ['offering_id'], unique=False)
    op.create_index(op.f('ix_learning_event_student_id'), 'learning_event', ['student_id'], unique=False)
    op.create_table('study_conversation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_conversation_offering_id'), 'study_conversation', ['offering_id'], unique=False)
    op.create_index(op.f('ix_study_conversation_student_id'), 'study_conversation', ['student_id'], unique=False)
    op.create_table('ai_generation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('faculty_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('source_item_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('succeeded','failed','invalid')", name='generation_status'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generation_offering_id'), 'ai_generation', ['offering_id'], unique=False)
    op.create_table('lesson_completion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('revision_version', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['learning_item.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'item_id', name='completion_unique')
    )
    op.create_index(op.f('ix_lesson_completion_student_id'), 'lesson_completion', ['student_id'], unique=False)
    op.create_table('study_message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('client_message_id', sa.String(length=64), nullable=True),
    sa.Column('reply_to_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant')", name='study_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['study_conversation.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['study_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_message_conversation_id'), 'study_message', ['conversation_id'], unique=False)
    op.create_index('one_client_message', 'study_message', ['conversation_id', 'client_message_id'], unique=True, postgresql_where=sa.text('client_message_id IS NOT NULL'))
    op.create_index('one_reply', 'study_message', ['reply_to_id'], unique=True, postgresql_where=sa.text('reply_to_id IS NOT NULL'))
    op.create_table('content_chunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('locator', sa.String(length=80), nullable=False),
    sa.Column('anchor_node_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, coalesce(title, '') || ' ' || text)", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['learning_item.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['learning_item_revision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'ordinal', name='chunk_ordinal_unique')
    )
    op.create_index('content_chunk_tsv', 'content_chunk', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_content_chunk_item_id'), 'content_chunk', ['item_id'], unique=False)
    op.create_index(op.f('ix_content_chunk_offering_id'), 'content_chunk', ['offering_id'], unique=False)
    op.create_index(op.f('ix_content_chunk_revision_id'), 'content_chunk', ['revision_id'], unique=False)
    op.create_table('reference_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("method IN ('fetched','manual')", name='snapshot_method'),
    sa.CheckConstraint("status IN ('extracted','approved')", name='snapshot_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['learning_item_revision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', name='snapshot_revision_unique')
    )
    op.add_column('assessment_revision', sa.Column('ai_generated', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('assessment_revision', sa.Column('reviewed_counter', sa.Integer(), nullable=True))
    op.add_column('assessment_revision', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.create_foreign_key('assessment_revision_reviewed_by_fkey', 'assessment_revision', 'account', ['reviewed_by'], ['id'])
    op.add_column('quiz_question', sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_question', 'source')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('assessment_revision_reviewed_by_fkey', 'assessment_revision', type_='foreignkey')
    op.drop_column('assessment_revision', 'reviewed_by')
    op.drop_column('assessment_revision', 'reviewed_counter')
    op.drop_column('assessment_revision', 'ai_generated')
    op.drop_table('reference_snapshot')
    op.drop_index(op.f('ix_content_chunk_revision_id'), table_name='content_chunk')
    op.drop_index(op.f('ix_content_chunk_offering_id'), table_name='content_chunk')
    op.drop_index(op.f('ix_content_chunk_item_id'), table_name='content_chunk')
    op.drop_index('content_chunk_tsv', table_name='content_chunk', postgresql_using='gin')
    op.drop_table('content_chunk')
    op.drop_index('one_reply', table_name='study_message', postgresql_where=sa.text('reply_to_id IS NOT NULL'))
    op.drop_index('one_client_message', table_name='study_message', postgresql_where=sa.text('client_message_id IS NOT NULL'))
    op.drop_index(op.f('ix_study_message_conversation_id'), table_name='study_message')
    op.drop_table('study_message')
    op.drop_index(op.f('ix_lesson_completion_student_id'), table_name='lesson_completion')
    op.drop_table('lesson_completion')
    op.drop_index(op.f('ix_ai_generation_offering_id'), table_name='ai_generation')
    op.drop_table('ai_generation')
    op.drop_index(op.f('ix_study_conversation_student_id'), table_name='study_conversation')
    op.drop_index(op.f('ix_study_conversation_offering_id'), table_name='study_conversation')
    op.drop_table('study_conversation')
    op.drop_index(op.f('ix_learning_event_student_id'), table_name='learning_event')
    op.drop_index(op.f('ix_learning_event_offering_id'), table_name='learning_event')
    op.drop_index(op.f('ix_learning_event_occurred_at'), table_name='learning_event')
    op.drop_table('learning_event')
    # ### end Alembic commands ###
