"""Teaching content drafts items announcements"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = 'f8b2e20a48f0'
down_revision = '48885aaab658'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('draft','published','archived')", name='announcement_state'),
    sa.ForeignKeyConstraint(['author_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_offering_id'), 'announcement', ['offering_id'], unique=False)
    op.create_table('learning_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('lesson','file','reference')", name='learning_item_kind'),
    sa.ForeignKeyConstraint(['created_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_item_offering_id'), 'learning_item', ['offering_id'], unique=False)
    op.create_table('syllabus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id')
    )
    op.create_table('teaching_coverage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('covered_on', sa.Date(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id', 'section_id', 'node_id', name='coverage_unique')
    )
    op.create_index(op.f('ix_teaching_coverage_offering_id'), 'teaching_coverage', ['offering_id'], unique=False)
    op.create_table('announcement_section',
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcement.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('announcement_id', 'section_id')
    )
    op.create_table('learning_item_revision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('draft_counter', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('reference_url', sa.String(length=2000), nullable=True),
    sa.Column('reference_note', sa.Text(), nullable=False),
    sa.Column('anchor_node_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('draft','published','superseded')", name='learning_item_state'),
    sa.ForeignKeyConstraint(['created_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['stored_file.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['learning_item.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'version', name='learning_item_version_unique')
    )
    op.create_index(op.f('ix_learning_item_revision_item_id'), 'learning_item_revision', ['item_id'], unique=False)
    op.create_index('one_item_draft', 'learning_item_revision', ['item_id'], unique=True, postgresql_where=sa.text("state = 'draft'"))
    op.create_index('one_item_published', 'learning_item_revision', ['item_id'], unique=True, postgresql_where=sa.text("state = 'published'"))
    op.create_table('learning_item_section',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['learning_item.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'section_id')
    )
    op.create_table('syllabus_revision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('syllabus_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('draft_counter', sa.Integer(), nullable=False),
    sa.Column('outline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grading_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_file_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('draft','published','superseded')", name='syllabus_state'),
    sa.ForeignKeyConstraint(['created_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['stored_file.id'], ),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('syllabus_id', 'version', name='syllabus_version_unique')
    )
    op.create_index(op.f('ix_syllabus_revision_syllabus_id'), 'syllabus_revision', ['syllabus_id'], unique=False)
    op.create_index('one_syllabus_draft', 'syllabus_revision', ['syllabus_id'], unique=True, postgresql_where=sa.text("state = 'draft'"))
    op.create_index('one_syllabus_published', 'syllabus_revision', ['syllabus_id'], unique=True, postgresql_where=sa.text("state = 'published'"))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('one_syllabus_published', table_name='syllabus_revision', postgresql_where=sa.text("state = 'published'"))
    op.drop_index('one_syllabus_draft', table_name='syllabus_revision', postgresql_where=sa.text("state = 'draft'"))
    op.drop_index(op.f('ix_syllabus_revision_syllabus_id'), table_name='syllabus_revision')
    op.drop_table('syllabus_revision')
    op.drop_table('learning_item_section')
    op.drop_index('one_item_published', table_name='learning_item_revision', postgresql_where=sa.text("state = 'published'"))
    op.drop_index('one_item_draft', table_name='learning_item_revision', postgresql_where=sa.text("state = 'draft'"))
    op.drop_index(op.f('ix_learning_item_revision_item_id'), table_name='learning_item_revision')
    op.drop_table('learning_item_revision')
    op.drop_table('announcement_section')
    op.drop_index(op.f('ix_teaching_coverage_offering_id'), table_name='teaching_coverage')
    op.drop_table('teaching_coverage')
    op.drop_table('syllabus')
    op.drop_index(op.f('ix_learning_item_offering_id'), table_name='learning_item')
    op.drop_table('learning_item')
    op.drop_index(op.f('ix_announcement_offering_id'), table_name='announcement')
    op.drop_table('announcement')
    # ### end Alembic commands ###
